/*
 * LIGHT_PRIVATE.h
 *
 *  Created on: Aug 27, 2026
 *      Author: DELL
 */

#ifndef INCLUDE_HAL_LIGHT_LIGHT_PRIVATE_H_
#define INCLUDE_HAL_LIGHT_LIGHT_PRIVATE_H_



#endif /* INCLUDE_HAL_LIGHT_LIGHT_PRIVATE_H_ */
