#ifndef INCLUDE_MCAL_TIMER1_TIMER1_CONFIG_H_
#define INCLUDE_MCAL_TIMER1_TIMER1_CONFIG_H_

/* Select Timer1 Mode:
 * Options:
 * 1. TIMER1_NORMAL_MODE
 * 2. TIMER1_CTC_OCR1A_TOP
 * 3. TIMER1_CTC_ICR1_TOP
 * 4. TIMER1_FAST_PWM_10BIT
 * 5. TIMER1_FAST_PWM_ICR1_TOP (Common for Servo & Custom Frequency PWM)
 * 6. TIMER1_FAST_PWM_OCR1A_TOP
 */
#define TIMER1_MODE           TIMER1_NORMAL_MODE

/* Select Clock Prescaler:
 * Options:
 * 1. TIMER1_STOP
 * 2. TIMER1_DIV_BY_1
 * 3. TIMER1_DIV_BY_8
 * 4. TIMER1_DIV_BY_64
 * 5. TIMER1_DIV_BY_256
 * 6. TIMER1_DIV_BY_1024
 */
#define TIMER1_PRESCALER      TIMER1_DIV_BY_64

#endif /* INCLUDE_MCAL_TIMER1_TIMER1_CONFIG_H_ */
