/*
 * LCD_PRIVATE.h
 *
 *  Created on: Aug 19, 2026
 *      Author: HP
 */

#include "../../LIB/BIT_MATH.h"
#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_



#define FUNCTION_SET 	    	CONC_BIT(0,0,1,LCD_DL,LCD_NO_OF_LINES,LCD_CHAR_FONT,0,0)
#define DISPLAY_ON_OFF_CONTROL 	CONC_BIT(0,0,0,0,1,DISPLAY_ON,CURSOR_DISPLAY,CURSOR_BLINK)
#define DISPLAY_CLEAR    		0x01
#define ENTRY_MODE_SET 			CONC_BIT(0,0,0,0,0,1,LCD_DATA_DIRECTION,LCD_SHIFT)

#define LCD_ROW1_ADDRESS 127
#define LCD_ROW2_ADDRESS 191


#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */

